### ISSUE TITLE
Workaround for incorrectly identified drill file

### ISSUE THREAD

**Issue by ju5t** [bellmann/pcb.js#2]
It should probably be enough to change `stackupZip` to the following code (and include `whats-that-gerber`):

```javascript
function stackupZip(zip) {
  return jszip.loadAsync(zip)
    .then(zip => {
      const files = [];
      zip.forEach((path, file) => {
        if (!file.dir) {
          const layerType = whatsThatGerber(file)
          files.push(
            file
              .async("text")
              .then(contents => ({
                gerber: contents,
                filename: path,
                options: {
                  filetype: (layerType === 'drl') ? 'drill' : 'gerber'
                }
              }))
          );
        }
      });
      return Promise.all(files);
    })
}
```

Ref: 
https://github.com/mcous/gerber-plotter/issues/14#issuecomment-383952594
mcous/gerber-parser#23

**Comment by mcous** [comment]
Just FYI, this is actually a workaround for mcous/gerber-parser#23

**Comment by ju5t** [comment]
@mcous thanks, I've updated the subject and description.

**Comment by ju5t** [comment]
It turns out that `const layerType = whatsThatGerber(file)` should be `const layerType = whatsThatGerber(path)`.
