### ISSUE TITLE
Update whats-that-gerber dependency for tracespace next.15

### ISSUE THREAD

**Issue by ju5t** [bellmann/pcb.js#4]
tracespace@next.15 will introduce a breaking change in `whats-that-gerber`. We will have to update our code, e.g. `countLayers()`.

Ref: https://github.com/tracespace/tracespace/pull/77

**Comment by mcous** [comment]
`whats-that-gerber@4.0.0-next.15` has just been released! Let me know if you run into any problems with the upgrade

**Comment by ju5t** [comment]
Thanks @mcous. I'm still testing a few things but so far so good. I'll probably push them tomorrow.
